---
project_name: govmomi
env:
  - CGO_ENABLED=0
builds:
  - id: govc
    binary: govc
    main: ./govc/
    flags: -compiler gc -tags 'netgo'
    ldflags: -X github.com/vmware/govmomi/version.GitVersion={{.Version}} -s -w
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - arm
      - amd64
      - 386
  - id: homebrew-govc
    binary: govc
    main: ./govc/
    flags: -compiler gc -tags 'netgo'
    ldflags: -X github.com/vmware/govmomi/version.GitVersion={{.Version}} -s -w
    goos:
      - darwin
    goarch:
      - amd64
  - id: vcsim
    binary: vcsim
    main: ./vcsim/
    flags: -compiler gc -tags 'netgo'
    ldflags: -X github.com/vmware/govmomi/version.GitVersion={{.Version}} -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - arm
      - amd64
      - 386
  - id: homebrew-vcsim
    binary: vcsim
    main: ./vcsim/
    flags: -compiler gc -tags 'netgo'
    ldflags: -X github.com/vmware/govmomi/version.GitVersion={{.Version}} -s -w
    goos:
      - darwin
    goarch:
      - amd64
  - id: toolbox
    binary: toolbox
    env:
    - CGO_ENABLED=0
    main: ./toolbox/toolbox/
    flags: -compiler gc -tags 'netgo'
    ldflags: -X github.com/vmware/govmomi/version.GitVersion={{.Version}} -s -w
    goos:
      - linux
    goarch:
      - amd64
      - 386
archives:
  - id: govc
    builds:
      - govc
    name_template: 'govc_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*
  - id: vcsim
    builds:
      - vcsim
    name_template: 'vcsim_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*
  - id: toolbox
    builds:
      - toolbox
    name_template: 'toolbox_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: gz
    files:
      - none*
  - id: homebrew-govc
    builds:
      - homebrew-govc
    name_template: 'govc-homebrew_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
  - id: homebrew-vcsim
    builds:
      - homebrew-vcsim
    name_template: 'vcsim-homebrew_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
brews:
  - 
    name: govc
    ids:
      - homebrew-govc
    github:
      owner: govmomi
      name: homebrew-tap
    commit_author:
      name: Alfred the Narwhal
      email: cna-alfred@vmware.com
    folder: Formula
    homepage: "https://github.com/vmware/govmomi/blob/master/govc/README.md"
    description: "govc is a vSphere CLI built on top of govmomi."
    test: |
      system "#{bin}/govc version"
    install: |
      bin.install "govc"
  - 
    name: vcsim
    ids:
      - homebrew-vcsim
    github:
      owner: govmomi
      name: homebrew-tap
    commit_author:
      name: Alfred the Narwhal
      email: cna-alfred@vmware.com
    folder: Formula
    homepage: "https://github.com/vmware/govmomi/blob/master/vcsim/README.md"
    description: "vcsim is a vSphere API simulator built on top of govmomi."
    test: |
      system "#{bin}/vcsim -h"
    install: |
      bin.install "vcsim"
dockers:
- image_templates: 
  - "vmware/govc:{{ .Tag }}"
  - "vmware/govc:v{{ .Major }}"
  - "vmware/govc:v{{ .Major }}.{{ .Minor }}"
  - "vmware/govc:latest"
  goos: linux
  goarch: amd64
  dockerfile: Dockerfile.govc
  binaries: 
  - govc
- image_templates: 
  - "vmware/vcsim:{{ .Tag }}"
  - "vmware/vcsim:v{{ .Major }}"
  - "vmware/vcsim:v{{ .Major }}.{{ .Minor }}"
  - "vmware/vcsim:latest"
  goos: linux
  goarch: amd64
  dockerfile: Dockerfile.vcsim
  binaries: 
  - vcsim
